name: information-discovery
description: Information Discovery NLP and ML platform
version: 0.12.0
apiVersion: v1
keywords:
  - information-discovery
appVersion: "6.1.0"
home: https://averbis.com/
icon: https://averbis.com/wp-content/uploads/2020/09/averbis_information_discovery.png
maintainers:
  - name: averbis
    email: info@averbis.com
    url: https://averbis.com
