apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml -o information-discovery
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: gcm
  name: gcm
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gcm
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yml -o information-discovery
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: gcm
    spec:
      imagePullSecrets:
      - name: averbis-docker-registry
      containers:
        - env:
            - name: GCM_HOSTNAME
              value: gcm
            - name: GCM_PORT
              value: "8181"
            - name: JAVA_MAX_MEM
              value: 2g
            - name: PLATFORM_HOSTNAME
              value: information-discovery
            - name: PLATFORM_PORT
              value: "8080"
            - name: PLATFORM_URL_NAME
              value: information-discovery
          image: registry.averbis.com/gcm/gcm:6.5.0
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8181/connector-manager/testConnectivity
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          name: gcm
          ports:
            - containerPort: 8181
          resources: 
            requests:
              memory: "2Gi"
          volumeMounts:
            - mountPath: /opt/resources/connector-manager/home
              name: gcmvol
      restartPolicy: Always
      volumes:
        - name: gcmvol
          persistentVolumeClaim:
            claimName: gcmvol
status: {}
